{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/carcare3/Actions/com_sap_mdk_Eyasset_CLONING/Service/UploadOffline.action",
    "OnFailure": "/carcare3/Actions/com_sap_mdk_Eyasset_CLONING/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}