{
	"_Type": "Action.Type.ClosePage",
	"ActionResult": {
		"_Name": "CreateCustomerCancel"
	},
	"DismissModal": "Action.Type.ClosePage.Canceled",
	"CancelPendingActions": true,
	"NavigateBackToPage": "LandingScreen"
}